### ISSUE TITLE
VBET 0.8.6 - Problem B. - Missing Centerlines and IGOs for some larger mainstem levelpaths.

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#701]
> The Cub River is missing a centerline. This is a known issue that's been documented a few times (ex. https://github.com/Riverscapes/riverscapes-tools/issues/696, https://github.com/Riverscapes/riverscapes-tools/issues/691, https://github.com/Riverscapes/riverscapes-tools/issues/697).

**Comment by jtgilbert** [comment]
This issue is duplicated 3 times and has been solved by rscontext/channel area update. Closing all but 1 issue.

**Comment by shelbysawyer** [comment]
@jtgilbert I'm still seeing this problem in 0.8.9 projects. I know this was closed because there were duplicates, but I can't find the issue that was left open..

**Comment by jtgilbert** [comment]
@shelbysawyer yeah this will be a problem until we do cyber castor runs using V2 xml. I closed because we know the problem and have the solution, it just won't be implemented in cybercastor V1 runs.
